apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.apiPort }}
      targetPort: {{ .Values.apiPort }}
      protocol: TCP
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
